### ISSUE TITLE
Configure fails to get leptonica include dir

### ISSUE THREAD

**Issue by Enchufa2** [ropensci/tesseract#61] opened 2022-09-23 08:48 UTC
Tesseract 5.2 (in Fedora 37+) no longer requires leptonica in its .pc file. As a result, installation fails because the configure script does not get its include dir. [Example](https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-37-x86_64/04868966-R-CRAN-tesseract/builder-live.log.gz):

```
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-L/usr/lib -ltesseract 
Using CXX11CPP: g++ -m64 -E -std=gnu++11
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find 'tesseract' system library. Try installing:
 * deb: libtesseract-dev libleptonica-dev (Debian, Ubuntu, etc)
 * rpm: tesseract-devel leptonica-devel (Fedora, CentOS, RHEL)
 * brew: tesseract (Mac OSX)
If tesseract is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a tesseract.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
tools/test.cpp:2:10: fatal error: allheaders.h: No such file or directory
    2 | #include <allheaders.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package 'tesseract'
```

An additional to `pkg-config --cflags --silence-errors lept` would be required.

**Comment by jeroen** [comment] 2022-09-23 10:03
Are you sure this not a bug in Fedora's tesseract package? On homebrew the `leptonica.pc` file has not changed:

```
prefix=/usr/local/Cellar/tesseract/5.2.0
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
datarootdir = /usr/local/share
datadir=${datarootdir}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: tesseract
Description: An OCR Engine that was developed at HP Labs between 1985 and 1995... and now at Google.
URL: https://github.com/tesseract-ocr/tesseract
Version: 5.2.0
Requires.private: lept
Libs: -L${libdir} -ltesseract -L/usr/local/Cellar/libarchive/3.6.1/lib -larchive -lcurl
Libs.private: -lpthread
Cflags: -I${includedir}
```

**Comment by Enchufa2** [comment] 2022-09-23 10:15
@manisandro I see in the changelog that you did the update. Any idea?

**Comment by jeroen** [comment] 2022-09-23 10:16
It has not changed upstream: https://github.com/tesseract-ocr/tesseract/blob/HEAD/tesseract.pc.in#L13

**Comment by Enchufa2** [comment] 2022-09-23 10:19
That's not the one that is used in cmake-based installations. This one is: https://github.com/tesseract-ocr/tesseract/blob/main/tesseract.pc.cmake

**Comment by Enchufa2** [comment] 2022-09-23 10:23
It seems so. Here: https://src.fedoraproject.org/rpms/tesseract/c/622725d18425696cdca5447558fd9e3ca892f858?branch=rawhide

@jeroen Thanks for the quick patch.

@manisandro Do you think we could add this downstream until upstream fixes this?

**Comment by jeroen** [comment] 2022-09-23 10:28
Upstream has merged it already. Maybe you can cherry-pick this for the rpm: https://github.com/tesseract-ocr/tesseract/commit/aee19fcf8eb832

**Closed** 2022-09-23 10:30 UTC

**Comment by manisandro** [comment] 2022-09-23 11:19
Done for tesseract-5.2.0-5.fc37 and tesseract-5.2.0-5.fc38.
