### ISSUE TITLE
Poorer performance

### ISSUE THREAD

**Issue by trinker** [ropensci/tesseract#2] opened 2016-11-15 14:31 UTC
I'm getting poorer performance.  I suspect I'm not understanding something.  Here is a link to a gist with code, pic, and output: https://gist.github.com/trinker/c24a0b56be1aa2cd22d4999a4e0f822c

```
if (!require("pacman")) install.packages("pacman")
pacman::p_load_current_gh('ropensci/tesseract', 'trinker/textreadr')
pacman::p_load(tiff)

img_url <- 'https://cloud.githubusercontent.com/assets/1763278/20309374/b47bd736-ab15-11e6-82df-215f79d0e8d2.png'
img_loc <- download(img_url)


# Extract text from images
out <- ocr(img_loc)
cat(out)
```

results in:

```
Dog
Fm m, me use W
Tins made )5 about me aomesuo aog For related speaes Imown as "dogs", see Camdae For Other uses, see Dag
"Dogg)e"IedIIec{s here Folme uamsn must, see Daggre (arm)
The domestic dog {Cams lupus rammans or Cams [Emma/Is)“ s 2 member 0' genus cams {canines) Inzl lorms pan
onne wolHIke cams“! and 5 me most wney abundant canmore ““5"“! The dog and me extant gray wonzre ssler
laxammm wnn modern wolves not closely related Io me wolves that were ﬁrst domesticated I‘ll?! smoe ns
domestication, me dog has been seleclwely bred over mlllennla [or vznous benzvms, sensory capamlmes, 2nd
pnysxzal zllnbules “"1
Their long assoclallon wnn humans has led Io dogs belllg umquely zlluned Io numzn benzvmm‘ and are me lo
Hume on 2 slarcnrncn dlel much would be Inadequate [or other can} speoes “1| Dogs are ago the oldest
domesticated ammal Dogs vzly wney m shape, SlZe and colours “3! Dogs peﬂorm many roles [or people, such as
nummg, nemmg, puumg loads, prolecllon, asslsllllg pollce 2nd mnnary, companlonsmp and, more reoenw, mug
handicapped mammals Tns Inﬂuence on human soclew nzs gwen Inem me sobnquel, "man‘s best mend"
```

**Comment by jeroenooms** [comment] 2016-11-15 14:39
I don't understand what you're trying to do with pacman / textreadr / etc. Are you comparing against some other OCR?

**Comment by jeroenooms** [comment] 2016-11-15 14:46
The main issue is simply that the quality of your image is low. If you increase the resolution a bit, the accuracy will rapidly increase. Try this image: 

```r
tesseract::ocr("https://cloud.githubusercontent.com/assets/216319/20310002/82eed2ce-ab4a-11e6-868b-72f480d01b1b.png")
```

<img width="923" alt="dog" src="https://cloud.githubusercontent.com/assets/216319/20310002/82eed2ce-ab4a-11e6-868b-72f480d01b1b.png">

**Comment by jeroenooms** [comment] 2016-11-15 14:57
Can I use your example in the blog post?

**Comment by trinker** [comment] 2016-11-15 15:10
Yes sure.  Sorry about the pacman.  It's part of my workflow as is the textreadr.  Feel free to replace with calls to more common packages.

**Comment by jeroenooms** [comment] 2016-11-15 19:54
OK I'm going to close this issue. The problem is simply the resolution of your image.

**Closed by jeroenooms** 2016-11-15 19:54 UTC

**Comment by trinker** [comment] 2016-11-15 20:03
Thanks and thanks for the package.

PS to others... I used https://sourceforge.net/projects/imageenlarger/ to improve resolution (this is not an area I know much about).  It was easy to set up and the results were great.

**Comment by trinker** [comment] 2016-11-15 20:26
Wondering if there would be room for a resolution improvement function using some command line tool wrapper for tesseract?

**Comment by jeroenooms** [comment] 2016-11-15 20:35
I highly doubt that artificially increasing resolution will add any useful quality to an image...

**Comment by trinker** [comment] 2016-11-16 02:43
@jeroenooms When I used the artificial (I assume it's interpolating or something like that) resolution resizing, it made the orc nearly perfect.  I took the original image and changed the width to 1000 and then increased sharpen, presharpen, and denoise parameters to 100 and here's the output:

```
Dog
From Wakipedia. the free encyclopedia
This article is about the domestic dog, For related species known as "dogs", see Canldae. For other uses, see Dog
"Doggie" redirects here. For the Danish artist, see Doggie (artist).
The domestic dog (Canis lupus familiaris or Canis familiarisﬂz’ is a member of genus Cam's (canines) that forms part
of the wolf-like canids,‘31 and is the most widely abundant carnivorelmsusl The dog and the extant gray wolf are sister
taxa,ml""91 with modern wolves not closely related to the wolves that were ﬁrst domesticated1315’l Since its
domestication, the dog has been selectively bred over millennia for various behaviors, sensory capabilities, and
physical attributes,“01
Their long association with humans has led to dogs being uniquely attuned to human behavior["'1 and are able to
thrive on a starch-rich diet which would be inadequate for other canid speciesm’ Dogs are also the oldest
domesticated animal. Dogs vary widely in shape. size and colours“! Dogs perform many roles for people, such as
hunting, herding, pulling loads, protection, assisting police and military, companionship and, more recently. aiding
handicapped individuals. This inﬂuence on human society has given them the sobriquet, "man‘s best friend".
```

**Comment by jeroenooms** [comment] 2016-11-16 04:18
Hmm you should suggest that to the tesseract folks. If that really works they should incorporate it.
